/* echo-client.c - Networking echo client */

/*
 * Copyright (c) 2017 Intel Corporation.
 * Copyright (c) 2018 Nordic Semiconductor ASA.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * The echo-client application is acting as a client that is run in Zephyr OS,
 * and echo-server is run in the host acting as a server. The client will send
 * either unicast or multicast packets to the server which will reply the packet
 * back to the originator.
 *
 * In this sample application we create four threads that start to send data.
 * This might not be what you want to do in your app so caveat emptor.
 */

#include <logging/log.h>
LOG_MODULE_REGISTER(net_echo_client_sample, LOG_LEVEL_DBG);

#include <zephyr.h>
#include <errno.h>
#include <stdio.h>

#include <net/socket.h>
#include <net/net_config.h>

#include "common.h"

#define APP_BANNER "Run echo client"

#define INVALID_SOCK (-1)

/* Generated by http://www.lipsum.com/
 * 2 paragraphs, 179 words, 1160 bytes of Lorem Ipsum
 */
const char lorem_ipsum[] =
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque "
	"sodales lorem lorem, sed congue enim vehicula a. Sed finibus diam sed "
	"odio ultrices pharetra. Nullam dictum arcu ultricies turpis congue, "
	"vel venenatis turpis venenatis. Nam tempus arcu eros, ac congue libero "
	"tristique congue. Proin velit lectus, euismod sit amet quam in, "
	"maximus condimentum urna. Cras vel erat luctus, mattis orci ut, varius "
	"urna. Nam eu lobortis velit."
	"\n"
	"Nullam sit amet diam vel odio sodales cursus vehicula eu arcu. Proin "
	"fringilla, enim nec consectetur mollis, lorem orci interdum nisi, "
	"vitae suscipit nisi mauris eu mi. Proin diam enim, mollis ac rhoncus "
	"vitae, placerat et eros. Suspendisse convallis, ipsum nec rhoncus "
	"aliquam, ex augue ultrices nisl, id aliquet mi diam quis ante. "
	"Pellentesque venenatis ornare ultrices. Quisque et porttitor lectus. "
	"Ut venenatis nunc et urna imperdiet porttitor non laoreet massa. Donec "
	"eleifend eros in mi sagittis egestas. Sed et mi nunc. Nunc vulputate, "
	"mauris non ullamcorper viverra, lorem nulla vulputate diam, et congue "
	"dui velit non erat. Duis interdum leo et ipsum tempor consequat. In "
	"faucibus enim quis purus vulputate nullam."
	"\n";

const int ipsum_len = sizeof(lorem_ipsum) - 1;

struct data conf = {
	.sock = INVALID_SOCK,
};

static struct zsock_pollfd fds;

static volatile bool in_process = false;

static void prepare_fds(void)
{
	fds.fd = conf.sock;
	fds.events = ZSOCK_POLLIN | ZSOCK_POLLOUT;
}

static int wait_event( int timeout)
{
	int ret;
	/*
	 * Check if any event occurred on fds poll fds.
	 */
	ret = zsock_poll(&fds, 1, timeout);
	if ( ret < 0 )
		LOG_ERR("Error in poll:%d", errno);

	if(fds.revents & ZSOCK_POLLIN) {
		LOG_INF("Event IN");
		if (in_process == false) {
			in_process = true;
		}

	}

	if(fds.revents & ZSOCK_POLLHUP)
		LOG_INF("Event HUP");

	if(fds.revents & ZSOCK_POLLOUT)
		LOG_INF("Event OUT");

	if(fds.revents & ZSOCK_POLLERR)
		LOG_INF("Event ERR");

	LOG_INF("Got event %d",fds.revents);

	return ret;
}

void main(void)
{
	int ret;

	LOG_INF(APP_BANNER);

reconnect:

	LOG_INF("Call start_tcp");
	ret = start_tcp();
	if (ret < 0)
		goto quit;

	send_tcp_data();

	prepare_fds();

	while (true) {
		// avoid call process_tcp() twice
		if ( in_process == true)
		{
			LOG_INF("Processing incomming data");
			ret = process_tcp();
			in_process = false;
			if (ret < 0)
				goto quit;

		}
		wait_event(-1);
	}

quit:
	LOG_INF("Stopping...");
	stop_tcp();

	k_sleep(5000);
	LOG_INF("Reconnecting...");
	goto reconnect;
}
